apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-username: cG9zdGdyZXM= #  base64 encoded value of 'postgres'
  postgres-password: cG9zdGdyZXM= #  base64 encoded value of 'postgres'
